nome = str(input('Digite seu nome completo:')).strip()
print('Analizando...')
nomeseparado = nome.split()
print('Seu nome em MAIUSCULO é {}'.format(nome.upper()))
print('Seu nome em minusculo é {}'.format(nome.lower()))
print('Seu nome tem {} letras'.format(len(nome) - nome.count(" ")))
print('Seu primeio nome é {} e tem {} letras'.format(nomeseparado[0], len(nomeseparado[0])))